/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thiago
 */
public class Estoque_Item extends javax.swing.JFrame {

    /**
     * Creates new form Estoque_Item
     */
    public Estoque_Item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        txtProdutoNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUnidades = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtCodico = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();
        btnIncluir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unidade", "Nome", "Preço", "Códico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTabela);

        btnIncluir.setText("Incluir");
        btnIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        txtProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("NOME:");

        jLabel2.setText("UNIDADES");

        txtUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesActionPerformed(evt);
            }
        });

        jLabel3.setText("CÓDICO");

        jLabel4.setText("PREÇO");

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        txtCodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodicoActionPerformed(evt);
            }
        });

        btnMenu.setText("jButton1");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnIncluir1.setText("Excluir");
        btnIncluir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnIncluir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(btnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98)
                .addComponent(btnMenu)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodico, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu)
                    .addComponent(btnIncluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   Estoque Metado = new Estoque();
   Menu a = new Menu();
    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
     boolean Subpasta  = new File("C:\\MercadoEstoque").mkdir();
     
     String[] linhas = new String[]{
         txtUnidades.getText(),
         txtProdutoNome.getText(),
         txtPreco.getText(),
         txtCodico.getText()
     };
     
     File arquivo  = new File("C:\\MercadoEstoque\\" + txtProdutoNome.getText()+ ".txt");
     try(BufferedWriter bw = new BufferedWriter(new FileWriter(arquivo))){
         for(String linha: linhas){
             bw.write(linha);
             bw.newLine();
         }
     }  catch (IOException ex) {
           JOptionPane.showMessageDialog(null, "Deu errad000o");
        }
    }//GEN-LAST:event_btnIncluirActionPerformed
   
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
         /*DefaultTableModel Tabela = ( DefaultTableModel) tblTabela.getModel();
          
          
          
        try {
            Files.walk(Paths.get("C:\\MercadoEstoque")).forEach((Path filePath) -> {
                if (Files.isRegularFile(filePath)) {
                    int i = 0;
                    int coluna = 0;
                    
                    
                    Object inserindo2 = new Object();
                    Object inserindo3 = new Object();
                    Object inserindo4 = new Object();
                    Object inserindo5 = new Object();
                    
                    Scanner sc = null;
                    try {
                        sc = new Scanner(filePath);
                        while(sc.hasNextLine()){
                            
                            if(i == 0){
                                    inserindo2 = sc.nextLine();
                             }
                              
                            if(i == 1){
                                    inserindo3 = sc.nextLine();
                             }
                            if(i == 2){
                                    inserindo4 = sc.nextLine();
                             }
                            if(i == 3){
                                    inserindo5 = sc.nextLine();
                             }
                                i = 1 + i;
                            }
                            i = 0;
                            coluna  = 1 + i;
                            Object[] inserindo = new Object[]{
                                inserindo2, 
                                  inserindo3, 
                                 inserindo4,
                                 inserindo5   
                            };
                             Tabela.addRow( inserindo);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Estoque_Item.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Estoque_Item.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    finally{
                        if( sc != null){
                            sc.close();
                        }
                    }       
                }
            });     
        } catch (IOException ex) {
            Logger.getLogger(Estoque_Item.class.getName()).log(Level.SEVERE, null, ex);
        }
         
       */
        
        /*File arquivo = new File("C:\\MercadoEstoque\\4.txt");
        Scanner sc = null;
        try{
           
        }
        catch( IOException e){
            JOptionPane.showMessageDialog(null, "errado");
        }
        finally{
            if( sc != null){
                sc.close();
            
        }
        */
       
    }//GEN-LAST:event_btnMenuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    DefaultTableModel Tabela = ( DefaultTableModel) tblTabela.getModel();
          
          
          
        try {
            Files.walk(Paths.get("C:\\MercadoEstoque")).forEach((Path filePath) -> {
                if (Files.isRegularFile(filePath)) {
                    int i = 0;
                    int coluna = 0;
                    
                    
                    Object inserindo2 = new Object();
                    Object inserindo3 = new Object();
                    Object inserindo4 = new Object();
                    Object inserindo5 = new Object();
                    
                    Scanner sc = null;
                    try {
                        sc = new Scanner(filePath);
                        while(sc.hasNextLine()){
                            
                            if(i == 0){
                                    inserindo2 = sc.nextLine();
                             }
                              
                            if(i == 1){
                                    inserindo3 = sc.nextLine();
                             }
                            if(i == 2){
                                    inserindo4 = sc.nextLine();
                             }
                            if(i == 3){
                                    inserindo5 = sc.nextLine();
                             }
                                i = 1 + i;
                            }
                            i = 0;
                            coluna  = 1 + i;
                            Object[] inserindo = new Object[]{
                                inserindo2, 
                                  inserindo3, 
                                 inserindo4,
                                 inserindo5   
                            };
                             Tabela.addRow( inserindo);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Estoque_Item.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Estoque_Item.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    finally{
                        if( sc != null){
                            sc.close();
                        }
                    }       
                }
            });     
        } catch (IOException ex) {
            Logger.getLogger(Estoque_Item.class.getName()).log(Level.SEVERE, null, ex);
        }
         
       
    }//GEN-LAST:event_formWindowOpened
 
    private void txtUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesActionPerformed

         
    }//GEN-LAST:event_txtUnidadesActionPerformed

    private void txtProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoNomeActionPerformed
        
    }//GEN-LAST:event_txtProdutoNomeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
          
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtCodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodicoActionPerformed
       
    }//GEN-LAST:event_txtCodicoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnIncluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluir1ActionPerformed
      DefaultTableModel Tabela = ( DefaultTableModel) tblTabela.getModel();
      
    }//GEN-LAST:event_btnIncluir1ActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque_Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnIncluir1;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtCodico;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProdutoNome;
    private javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables
}
